# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  coffeescript = nodeEnv.buildNodePackage {
    name = "coffeescript";
    packageName = "coffeescript";
    version = "2.6.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/coffeescript/-/coffeescript-2.6.1.tgz";
      sha512 = "GG5nkF93qII8HmHqnnibkgpp/SV7PSnSPiWsbinwya7nNOe95aE/x2xrKZJFks8Qpko3TNrC+/LahaKgrz5YCg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Unfancy JavaScript";
      homepage = "https://coffeescript.org";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
